#ifdef __cplusplus
extern "C" { 
#endif 

#include "HROOTType.h"

#include "HROOTTDictionary.h"
#include "HROOTTNamed.h"
#include "HROOTTObject.h"
#include "HROOTDeletable.h"

#undef ROOT_TCLASS_DECLARATIONVIRT
#define ROOT_TCLASS_DECLARATIONVIRT(Type) \


#undef ROOT_TCLASS_DECLARATIONNONVIRT
#define ROOT_TCLASS_DECLARATIONNONVIRT(Type) \


#undef ROOT_TCLASS_DEFINITIONVIRT
#define ROOT_TCLASS_DEFINITIONVIRT(Type)\


#undef ROOT_TCLASS_DEFINITIONNONVIRT
#define ROOT_TCLASS_DEFINITIONNONVIRT(Type)\


ROOT_TDICTIONARY_DECLARATIONVIRT(TClass);
ROOT_TNAMED_DECLARATIONVIRT(TClass);
ROOT_TOBJECT_DECLARATIONVIRT(TClass);
ROOT_DELETABLE_DECLARATIONVIRT(TClass);


ROOT_TCLASS_DECLARATIONVIRT(TClass);


ROOT_TCLASS_DECLARATIONNONVIRT(TClass);


#ifdef __cplusplus
}
#endif
